### ISSUE TITLE
Error when connecting from mysql client 8.0.22

### ISSUE THREAD

**Issue by gonzus** [CloudQuote/faux-mysql-server#1]
Just in case there is someone still on the other side... :-)  This is running on node version 14.15.3.

I run `node lib/example.js` (where the transpiled `example.js` lives), with the port switched to 3344, and on another terminal I run `mysql -h127.0.0.1 -P3344 -uXXX -pXXX`. The output is:

```
Started server on port 3344
internal/validators.js:129
    throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "byteLength" argument must be of type number. Received undefined
    at validateNumber (internal/validators.js:129:11)
    at boundsError (internal/buffer.js:76:5)
    at Buffer.readUIntLE (internal/buffer.js:181:3)
    at Server.readPackets (.../faux-mysql-server/lib/index.js:393:31)
    at Server.gatherIncoming (.../faux-mysql-server/lib/index.js:379:28)
    at Socket.Server.handleData (.../faux-mysql-server/lib/index.js:74:13)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by mdierolf** [comment]
I'm still here - just haven't put much more effort into this module. I was using it to mock a mysql interface for testing.

I have pushed an update to the module - I had an error in how I was parsing the packets, it should be working now, although it needs quite a bit of work to be considered production quality code.

Also it uses native ES modules now, and I have removed the transpiling with babel.

**Comment by gonzus** [comment]
Hey, thanks for the quick response! Yeah, this is much better now. Although I still get unexpected behavior. I run the example and see:
```
$ node example.js 
Started server on port 3344
```

Then on another window I run:
```
$ mysql -h127.0.0.1 -P3344 -ugonzo -pgonzo -Dworld
```

Then, the first window shows:
```
$ node example.js 
Started server on port 3344
Auth Info:
{
  clientFlags: <Buffer 8d a6 ff 01>,
  maxPacketSize: <Buffer 00 00 00 01>,
  username: 'gonzo',
  database: 'world'
}
disconnect
```

and the other window shows:
```
$ mysql -h127.0.0.1 -P3344 -ugonzo -pgonzo -Dworld
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

Notice that the Node process never prints `Disconnecting`, so this is not a case of the client sending a `COM_QUIT`. It looks like the `handleDisconnect()` handler is being called right away?

**Comment by mdierolf** [comment]
Should be fixed now. Once you receive the COM_QUIT message in your handler, then you need to call this.end() to close the connection.

This project is very much a work-in-progress, my goal was to build a quick implementation to test whether it would work and to allow me to debug various stream errors injections to debug a mysql client library

In the future this whole thing needs to be rebuilt. The library should use the event emitter pattern like a stream.

**Comment by gonzus** [comment]
I'm sorry, I tried pulling but there are no new commits and I still see that `disconnect` behavior. Perhaps you forgot to push?

**Comment by gonzus** [comment]
BTW, I intend to reuse / reimplement this with TypeScript, so if you think this is the way you want to go with this code, I would be happy to contribute to your repository.

**Comment by gonzus** [comment]
So, am I right in assuming that an additional change (maybe not committed yet) is needed to solve the `disconnect` issue I mentioned above? Or did you mean it is already solved with your two changes from yesterday? But if this is the case, I still see the symptom I described.

**Comment by mdierolf** [comment]
Apologies, I forgot to push my changes.
The disconnect issue should be resolved.

In the example.js file you will notice that upon COM_QUIT, I call this.end() to close the stream.

I would welcome any contributions to this project, it needs quite a lot of work.

**Comment by gonzus** [comment]
Thanks for that. So I don't see the fake server disconnecting anymore, but the mysql client immediately exits:
```
$ mysql -h127.0.0.1 -P3344 -ugonzo -pgonzo -Dworld
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
I added a `console.log` to `sendPacket()` and this is the whole output on the server:
```
$ node example.js 
Started Fake Mysql/1.0 on port 3344
sendPacket <Buffer 3c 00 00 00 0a 46 61 6b 65 20 4d 79 73 71 6c 2f 31 2e 30 00 8a 6e 01 00 f6 51 c4 48 f6 86 8f 3e 00 09 82 21 02 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 14 more bytes>
Auth Info:
{
  clientFlags: <Buffer 8d a6 ff 01>,
  maxPacketSize: <Buffer 00 00 00 01>,
  username: 'gonzo',
  database: 'world'
}
sendPacket <Buffer 0d 00 00 4e 00 00 fb 02 00 00 00 fd 02 00 00 4f 4b>
```
So it seems the server is sending back an invalid answer to the client, and the client closes?

**Comment by gonzus** [comment]
About the contributions, if I can get this example to:
* Allow a stock mysql client to connect.
* Receive simple queries from the client (such as `SELECT * FROM table`).
* Send crap data back to the client.

Then I will start proposing some PRs to clean up the code; before that, my own understanding of the code is too vague to be of any help. :-)

**Comment by gonzus** [comment]
Here is the output of running the mysql client against a real MySQL DB versus running it against the Faux server, in case this helps diagnose (I clipped some informational messages printed by the client). Unfortunately, I don't know enough about the network protocol to be able to make anything out of this.

 First as strings:
```
$ strace --trace recvfrom -v -s 256 mysql -A -h127.0.0.1 -P3306 -ugonzo -pgonzo -Dworld
recvfrom(3, "[\0\0\0\n8.0.22-0ubuntu0.20.04.3\0\35\0\0\0002\"\0044\36HV8\0\377\377\377\2\0\377\307\25\0\0\0\0\0\0\0\0\0\08LWx.|\0361s~g[\0caching_sha2_password\0", 16384, 0, NULL, NULL) = 95
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 29
Server version: 8.0.22-0ubuntu0.20.04.3 (Ubuntu)
mysql> ^DBye
+++ exited with 0 +++

$ strace --trace recvfrom -v -s 256 mysql -A -h127.0.0.1 -P3344 -ugonzo -pgonzo -Dworld
recvfrom(3, "<\0\0\0\nFake Mysql/1.0\0\t\222\1\0v?\375\307\224~2\233\0\t\202!\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\374\21\267\356\241\314\342\2504\23x\300\0", 16384, 0, NULL, NULL) = 64
recvfrom(3, "\r\0\0N\0\0\373\2\0\0\0\375\2\0\0OK", 16384, 0, NULL, NULL) = 17
ERROR 2013 (HY000): Lost connection to MySQL server during query
+++ exited with 1 +++
```

and now as hex values:
```
$ strace --trace recvfrom -x -v -s 256 mysql -A -h127.0.0.1 -P3306 -ugonzo -pgonzo -Dworld
recvfrom(3, "\x5b\x00\x00\x00\x0a\x38\x2e\x30\x2e\x32\x32\x2d\x30\x75\x62\x75\x6e\x74\x75\x30\x2e\x32\x30\x2e\x30\x34\x2e\x33\x00\x1e\x00\x00\x00\x7e\x2a\x28\x48\x2e\x16\x2a\x69\x00\xff\xff\xff\x02\x00\xff\xc7\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x66\x78\x36\x3e\x04\x4d\x2f\x22\x2b\x58\x4e\x03\x00\x63\x61\x63\x68\x69\x6e\x67\x5f\x73\x68\x61\x32\x5f\x70\x61\x73\x73\x77\x6f\x72\x64\x00", 16384, 0, NULL, NULL) = 95
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 30
Server version: 8.0.22-0ubuntu0.20.04.3 (Ubuntu)
mysql> ^DBye
+++ exited with 0 +++

$ strace --trace recvfrom -x -v -s 256 mysql -A -h127.0.0.1 -P3344 -ugonzo -pgonzo -Dworld
mysql: [Warning] Using a password on the command line interface can be insecure.
recvfrom(3, "\x3c\x00\x00\x00\x0a\x46\x61\x6b\x65\x20\x4d\x79\x73\x71\x6c\x2f\x31\x2e\x30\x00\x09\x92\x01\x00\x58\xba\xb7\x33\x9d\x94\x32\x02\x00\x09\x82\x21\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\x70\x0c\x6a\xa9\xdc\x85\xa4\x87\xc8\x5c\x6a\x00", 16384, 0, NULL, NULL) = 64
recvfrom(3, "\x0d\x00\x00\x4e\x00\x00\xfb\x02\x00\x00\x00\xfd\x02\x00\x00\x4f\x4b", 16384, 0, NULL, NULL) = 17
ERROR 2013 (HY000): Lost connection to MySQL server during query
+++ exited with 1 +++
```

**Comment by gonzus** [comment]
Just created https://github.com/CloudQuote/faux-mysql-server/pull/2 -- mostly for myself but there are some very minor improvements in there.

**Comment by mdierolf** [comment]
Just pushed another update - it seems like the official MySQL client is more strict with sequence numbers in the returned packet, the MariaDB client I use appears to ignore them, and we were not sending back the proper sequence #

**Comment by mdierolf** [comment]
BTW when you are trying to implement the MySQL protocol, Wireshark works extremely, it decodes every packet sent back and forth and will flag errors

**Comment by gonzus** [comment]
It works perfectly now! As in, I can send commands from the client, and get the fake responses; I can also `^D` out of the client and the connection is closed on the server. Will close this issue now.
